---
env:
  contexts:
  - name: "https://demo.testfire.net"
    urls:
    - "https://demo.testfire.net"
    includePaths:
    - "https://demo.testfire.net.*"
    excludePaths:
    - "https://demo.testfire.net/images/.*"
    authentication:
      method: "form"
      parameters:
        loginPageUrl: "https://demo.testfire.net/doLogin"
        loginRequestUrl: "https://demo.testfire.net/doLogin"
        loginRequestBody: "uid={%username%}&passw={%password%}&btnSubmit=Login"
      verification:
        method: "response"
        loggedInRegex: "\\Q<a id=\"LoginLink\" href=\"/logout.jsp\">\\E"
        loggedOutRegex: "\\Q<a id=\"LoginLink\" href=\"/login.jsp\">\\E"
        pollFrequency: 60
        pollUnits: "requests"
        pollUrl: ""
        pollPostData: ""
    sessionManagement:
      method: "cookie"
      parameters: {}
    users:
    - name: "test"
      credentials:
        password: "jsmith"
        username: "Demo1234"
  parameters:
    failOnError: true
    failOnWarning: false
    progressToStdout: true
  vars: {}
jobs:
- parameters:
    scanOnlyInScope: true
    enableTags: false
  rules: []
  name: "passiveScan-config"
  type: "passiveScan-config"
- parameters:
    context: "https://demo.testfire.net"
    user: "test"
    url: "https://demo.testfire.net"
    maxDuration: 0
    maxDepth: 0
    maxChildren: 0
  tests:
  - onFail: "ERROR"
    statistic: "stats.auth.state.loggedin"
    site: ""
    operator: ">="
    value: 1
    type: "stats"
    name: "Logged in at least once"
  name: "spider"
  type: "spider"
- parameters:
    template: "risk-confidence-html"
    reportDir: "/zap/wrk"
    reportTitle: "ZAP Scanning Report"
    reportDescription: ""
  name: "report"
  type: "report"
