---
env:
  contexts:
  - name: "https://demo.testfire.net"
    urls:
    - "https://demo.testfire.net"
    includePaths:
    - "https://demo.testfire.net.*"
    excludePaths:
    - "https://demo.testfire.net/images/.*"
    authentication:
      method: "form"
      parameters:
        loginPageUrl: "https://demo.testfire.net/doLogin"
        loginRequestUrl: "https://demo.testfire.net/doLogin"
        loginRequestBody: "uid={%username%}&passw={%password%}&btnSubmit=Login"
      verification:
        method: "response"
        loggedInRegex: "\\Q<a id=\"LoginLink\" href=\"/logout.jsp\">\\E"
        loggedOutRegex: "\\Q<a id=\"LoginLink\" href=\"/login.jsp\">\\E"
        pollFrequency: 60
        pollUnits: "requests"
        pollUrl: ""
        pollPostData: ""
    sessionManagement:
      method: "cookie"
      parameters: {}
    users:
    - name: "test"
      credentials:
        password: "${DAST_PASSWORD}"
        username: "${DAST_USERNAME}"
  parameters:
    failOnError: true
    failOnWarning: false
    progressToStdout: true
  vars: {}
jobs:
- parameters:
    scanOnlyInScope: true
    enableTags: false
  rules: []
  name: "passiveScan-config"
  type: "passiveScan-config"
- parameters:
    context: "https://demo.testfire.net"
    user: "test"
    url: "https://demo.testfire.net"
    maxDuration: 0
    maxDepth: 0
    maxChildren: 0
  tests:
  - onFail: "INFO"
    statistic: "automation.spider.urls.added"
    site: ""
    operator: ">="
    value: 100
    type: "stats"
    name: "At least 100 URLs found"
  name: "spider"
  type: "spider"
- parameters:
    context: "https://demo.testfire.net"
    user: "test"
    url: "https://demo.testfire.net"
    maxDuration: 30
    maxCrawlDepth: 10
    numberOfBrowsers: 1
    runOnlyIfModern: false
  tests:
  - onFail: "INFO"
    statistic: "spiderAjax.urls.added"
    site: ""
    operator: ">="
    value: 100
    type: "stats"
    name: "At least 100 URLs found"
  name: "spiderAjax"
  type: "spiderAjax"
- parameters:
    maxDuration: 0
  name: "passiveScan-wait"
  type: "passiveScan-wait"
- parameters:
    template: "risk-confidence-html"
    reportDir: "/zap/wrk"
    reportTitle: "ZAP Scanning Report"
    reportDescription: ""
  name: "report"
  type: "report"
