name: ZAP baseline Scan

on: 
  push:
    branches: ["zap-baseline-workflow"]
  pull_request:
    branches: ["zap-baseline-workflow"]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan ZAP website
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: 'https://demo.testfire.net/login.jsp'
          cmd_options: '-n demo.context --hook=my-hooks.py'
